<?php

if($a == $b) {
   echo "something";
}

if/**/($a == $b) {
	      echo "something";
}

	if ($a == $b) {
	echo "something";
	}

if(
$a == $b
&& $c > $d
) {
	echo "something";
}

  if($a == $b) {
	       echo "something";
} elseif($a && $b) {
	echo "Other stuff";
				$more = "stuff";
}

while(true) {
//do something
}

public function mario($cond) {
		while ($cond == true) {
	$test = true;
		}
}

do {
asd();
	     asd();
} while($asd);


$a = array(
			2 => 7,
3 => 8,
				6 => 9
		);

if (
true
&& false
) {
return 6;
}

$obj = $this
->do()
->something()
		;


