<?php

$asd = (substr(doMore("asdasd", "asdasd", -1))) ?
	doStuff(array("asdasd", "asdasdasdasd")) : "asddasdasdasdasdasdasd";


$asdasd = "asdasdasd"         ?           true       :        doMore();
$asdasd = "asdasdasd"?true:doMore();

function ciao() {
$asdasd = "asdasdasd"?true
:doMore();
	
}

$asdasd = "asdasdasd"


        ?








        true




             :






                   doMore();
