<?php

$a = array(5//ciao
 );

$a = array(
  6);

$a = array( 7,
// comment,,	,
	);

$a = array(	 9,
	/* comment , ,,,*/
 	);

$a = array(  2,
	// comment
	// ,

#comment
/*comment */
);

$a = array(substr("array", 2)
);

$a = array(
	#comment ,
	array(3,4)
#comment
);

$a = array(
	1,	        2
  );

$a = array(
	1,	array(2, 3));

$a = array(array(2, 3),1,substr("ciao", 1)
);

$a = array(
				array(
		2  				 => 1,
"3" => 6
	),
				1,
  substr("ciao", 1)
         );

function test() {

$a = array(
	"aasfasdas" => array(2, 3),
	"b"         => 1,
	"c"         => substr("ciao", 1),
	3           => count(array(2, 6))
);
}

$resurn = array("aasfasdas" =>      array(2, 3),
	"b"         => 1,	"c"         => substr("ciao", 1),
	3       		    => count(array(2, 6))
);

pippo(
array(
		"aasfasdas"     => array(2, 3),
		"b"     => 1,
		"c"         => substr("ciao", 1),
			3           => count(array(2, 6))
			)
);

$a = array(
3,4);

$a = array(3,4,
);

$a = array(
3,4,5
	);

$a = array(				3,
4,5,
count(array(3,
4
))
);

$a = array( "b" ,	"c",
3,4,);

$a = array( "b" ,	"c",
				array( 2 , 4,
				5),
			substr("asdfdf", 3),
3,4,);

$aasdfasdfasdfasdfasf = array( "b" => 5 ,	"c"   =>2,
				3=>array( 2 , 4,
				5),
"sdfasdf"=>			substr("asdfdf", 3),
9    =>3,"asd"=>"asdfsd",);

$a = array(
2,
"4"=> 6
	);
