<?php

$a = array(1);

$a = array(substr("array", 2));

$a = array(array(2, 5));

$a = array( 	2);

$a = array(3	  );

$a = array( 	4	 );

$a = array( 	8	 );

$a = array(1, 2);

$a = array(1, array(2, 3));

$a = array(array(2, 3), 1, substr("ciao", 1));

$a = array(array(2 => 1, "3" => 6), 1, substr("ciao", 1));

$a = array("a" => array(2, 3), "b" => 1, "c" => substr("ciao", 1));

$a = array( 	 1,2);

$a = array(1 	 ,2);

$a = array(1, 	 2);

$a = array(1,2 	 	);

$a = array(	 	 1 	 , 	 	2 	 		 );

$a = array(1,2,);

$a = array(1,2,	 	 	 	);

$a = array(	 	 	1	 	 	, 	 	 2 		 	, 	 );

$a = array(1,2,array(12,234));

$a = array(1,2,substr("ciao", 2));

$a = array(substr("ciao", 2), 1,2,array(2,3),);

$a = array(1,2);

$a = array( "a"  	=>  array(2 , 3),"b"=>1,   "c"  	 	=>  		 substr("ciao", 1),1=>3,);
